class PopulateAreas < ActiveRecord::Migration
  
LOCATION = [ "Adambakkam",
"Adyar",
"Alandur",
"Alwarpet",
"Alwarthirunagar",
"Ambattur",
"Aminjikarai",
"Anakaputhur",
"Anna Nagar",
"Annanur",
"Arumbakkam",
"Ashok Nagar",
"Avadi",
"Ayanavaram",
"Besant Nagar",
"Basin Bridge",
"Chepauk",
"Chetput",
"Chintadripet",
"Chitlapakkam",
"Choolai",
"Choolaimedu",
"Chrompet",
"Egmore",
"Ekkaduthangal",
"Ennore",
"Foreshore Estate",
"Fort St. George",
"George Town",
"Gopalapuram",
"Government Estate",
"Guindy",
"IIT Madras",
"Injambakkam",
"ICF",
"Iyyapanthangal",
"Jafferkhanpet",
"Karapakkam",
"Kattivakkam",
"Kazhipattur",
"k.K. Nagar",
"Keelkattalai",
"Kelambakkam",
"Kilpauk",
"Kodambakkam",
"Kodungaiyur",
"Kolathur",
"Korattur",
"Korukkupet",
"Kottivakkam",
"Kotturpuram",
"Kottur",
"Kovalam",
"Kovilambakkam",
"Koyambedu",
"Kundrathur",
"Madhavaram",
"Madhavaram Milk Colony",
"Madipakkam",
"Madambakkam",
"Maduravoyal",
"Manali",
"Manali New Town",
"Manapakkam",
"Mandaveli",
"Mangadu",
"Mannadi",
"Mathur",
"Medavakkam",
"Meenambakkam",
"MGR Nagar",
"Minjur",
"Mogappair",
"MKB Nagar",
"Mount Road",
"Moolakadai",
"Moulivakkam",
"Mugalivakkam",
"Mudichur",
"Mylapore",
"Nandanam",
"Nanganallur",
"Navalur",
"Neelankarai",
"Nemilichery",
"Nesapakkam",
"Nolambur",
"Noombal",
"Nungambakkam",
"Otteri",
"Padi",
"Pakkam",
"Palavakkam",
"Pallavaram",
"Pallikaranai",
"Pammal",
"Park Town",
"Parrys Corner",
"Pattabiram",
"Pattaravakkam",
"Pazhavanthangal",
"Peerkankaranai",
"Perambur",
"Peravallur",
"Perumbakkam",
"Perungalathur",
"Perungudi",
"Pozhichalur",
"Poonamallee",
"Porur",
"Pudupet",
"Purasaiwalkam",
"Puthagaram",
"Puzhal",
"Puzhuthivakkam",
"Raj Bhavan",
"Ramavaram",
"Red Hills",
"Royapettah",
"Royapuram",
"Saidapet",
"Saligramam",
"Santhome",
"Sembakkam",
"Selaiyur",
"Shenoy Nagar",
"Sholavaram",
"Sholinganallur",
"Sithalapakkam",
"Sowcarpet",
"st.Thomas Mount",
"Tambaram",
"Teynampet",
"Tharamani",
"T. Nagar",
"Thirumangalam",
"Thirumullaivoyal",
"Thiruneermalai",
"Thiruninravur",
"Thiruvanmiyur",
"Tiruverkadu",
"Thiruvotriyur",
"Tirusulam",
"Tiruvallikeni",
"Tondiarpet",
"United India Colony",
"Vandalur",
"Vadapalani",
"Valasaravakkam",
"Vallalar Nagar",
"Vanagaram",
"Velachery",
"Villivakkam",
"Virugambakkam",
"Vyasarpadi",
"Washermanpet",
"West Mambalam"
]

def change
LOCATION.each do |location|
execute("INSERT INTO location_areas (area,created_at, updated_at) VALUES ('#{location}',#{Time.now().to_i},#{Time.now().to_i})")
end
  end
end
